version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - frontend-beta
      - frontend
      - ssh_tunnel
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/java:/src/main/java
  frontend:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    environment:
      - DEV_SERVER_PORT=8081
      - PROXY_API_HOST=backend
      - PROXY_API_PORT=8080
    ports:
      - "8081:8081"
    volumes:
      - ./webapp:/webapp
  frontend-beta:
    build:
      context: .
      dockerfile: webapp-beta/Dockerfile
    environment:
      - DEV_SERVER_PORT=8082
      - PROXY_API_HOST=backend
      - PROXY_API_PORT=8080
    ports:
      - "8082:8082"
    volumes:
      - ./webapp-beta:/webapp-beta
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_DB=momus
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
  ssh_tunnel:
    image: ictu/sshpass
    command: sshpass -p ${SSH_PASSWORD} ssh -o StrictHostKeyChecking=no -4NL *:389:ldap.smint.no:389 ${SSH_USER}@login.smint.no
